# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arm_console_pb2 as arm__console__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arm_console_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArmGatewayStub:
    """Transport contract shared by the C++ gateway, Rust Viewer and ROS 2 tools.
    Units: radians, radians/second, meters, meters/second, nanoseconds.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/arm.console.v1.ArmGateway/Handshake',
                request_serializer=arm__console__pb2.ConnectRequest.SerializeToString,
                response_deserializer=arm__console__pb2.ConnectReply.FromString,
                _registered_method=True)
        self.Command = channel.unary_unary(
                '/arm.console.v1.ArmGateway/Command',
                request_serializer=arm__console__pb2.ControlCommand.SerializeToString,
                response_deserializer=arm__console__pb2.CommandAck.FromString,
                _registered_method=True)
        self.SubscribeTelemetry = channel.unary_stream(
                '/arm.console.v1.ArmGateway/SubscribeTelemetry',
                request_serializer=arm__console__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=arm__console__pb2.TelemetryFrame.FromString,
                _registered_method=True)


class ArmGatewayServicer:
    """Transport contract shared by the C++ gateway, Rust Viewer and ROS 2 tools.
    Units: radians, radians/second, meters, meters/second, nanoseconds.

    """

    def Handshake(self, request, context):
        """Named Handshake to avoid a method-name collision in generated Rust clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=arm__console__pb2.ConnectRequest.FromString,
                    response_serializer=arm__console__pb2.ConnectReply.SerializeToString,
            ),
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=arm__console__pb2.ControlCommand.FromString,
                    response_serializer=arm__console__pb2.CommandAck.SerializeToString,
            ),
            'SubscribeTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTelemetry,
                    request_deserializer=arm__console__pb2.TelemetryRequest.FromString,
                    response_serializer=arm__console__pb2.TelemetryFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arm.console.v1.ArmGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arm.console.v1.ArmGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArmGateway:
    """Transport contract shared by the C++ gateway, Rust Viewer and ROS 2 tools.
    Units: radians, radians/second, meters, meters/second, nanoseconds.

    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arm.console.v1.ArmGateway/Handshake',
            arm__console__pb2.ConnectRequest.SerializeToString,
            arm__console__pb2.ConnectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arm.console.v1.ArmGateway/Command',
            arm__console__pb2.ControlCommand.SerializeToString,
            arm__console__pb2.CommandAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arm.console.v1.ArmGateway/SubscribeTelemetry',
            arm__console__pb2.TelemetryRequest.SerializeToString,
            arm__console__pb2.TelemetryFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ArmPlannerStub:
    """Headless Pinocchio/ProxSuite planning boundary. Planning never actuates a
    robot; returned trajectories are candidates for ArmGateway safety checks.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolveIK = channel.unary_unary(
                '/arm.console.v1.ArmPlanner/SolveIK',
                request_serializer=arm__console__pb2.IKRequest.SerializeToString,
                response_deserializer=arm__console__pb2.IKResponse.FromString,
                _registered_method=True)
        self.PlanTrajectory = channel.unary_unary(
                '/arm.console.v1.ArmPlanner/PlanTrajectory',
                request_serializer=arm__console__pb2.TrajectoryPlanRequest.SerializeToString,
                response_deserializer=arm__console__pb2.TrajectoryPlanResponse.FromString,
                _registered_method=True)


class ArmPlannerServicer:
    """Headless Pinocchio/ProxSuite planning boundary. Planning never actuates a
    robot; returned trajectories are candidates for ArmGateway safety checks.
    """

    def SolveIK(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArmPlannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolveIK': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveIK,
                    request_deserializer=arm__console__pb2.IKRequest.FromString,
                    response_serializer=arm__console__pb2.IKResponse.SerializeToString,
            ),
            'PlanTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanTrajectory,
                    request_deserializer=arm__console__pb2.TrajectoryPlanRequest.FromString,
                    response_serializer=arm__console__pb2.TrajectoryPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arm.console.v1.ArmPlanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arm.console.v1.ArmPlanner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArmPlanner:
    """Headless Pinocchio/ProxSuite planning boundary. Planning never actuates a
    robot; returned trajectories are candidates for ArmGateway safety checks.
    """

    @staticmethod
    def SolveIK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arm.console.v1.ArmPlanner/SolveIK',
            arm__console__pb2.IKRequest.SerializeToString,
            arm__console__pb2.IKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arm.console.v1.ArmPlanner/PlanTrajectory',
            arm__console__pb2.TrajectoryPlanRequest.SerializeToString,
            arm__console__pb2.TrajectoryPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
