[workspace]
members = [
    "crates/egui-shadcn",
    "crates/iced-shadcn",
    "crates/iced-shadcn-v2",
    "crates/shadcn-common",
    "crates/shadcn-rs-cli",
    "crates/wasm-demo",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
version = "0.5.0"
authors = ["FerrisMind"]
homepage = "https://github.com/FerrisMind/shadcn-rs"
repository = "https://github.com/FerrisMind/shadcn-rs"
description = "Shadcn and Radix UI-inspired component library for the Rust GUI (egui)"

[workspace.dependencies]
log = "0.4"
env_logger = "0.11"
shadcn-common = { path = "crates/shadcn-common", version = "0.5.0" }
twill-core = { git = "https://github.com/FerrisMind/twill.git", rev = "83e8ac1a00766b5304ec88d25a9f3e99274ef0e8", version = "0.3.0" }
twill-iced = { git = "https://github.com/FerrisMind/twill.git", rev = "83e8ac1a00766b5304ec88d25a9f3e99274ef0e8", default-features = false }
tree-sitter = "0.25"
tree-sitter-bash = "0.25"
tree-sitter-css = "0.25"
tree-sitter-diff = "0.1"
tree-sitter-highlight = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-json = "0.24"
tree-sitter-rust = "0.24"
tree-sitter-svelte-next = "0.1"
tree-sitter-typescript = "0.23"
chorale-core = "0.2.3"
zxcvbn = "3.1.1"

[profile.dev]
incremental = true
opt-level = 1
debug = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
incremental = false
